version: 2

sources:
  - name: raw
    database: WESFARMERS_API_RECOMMENDER
    schema: RAW
    tables:
      - name: raw_members
      - name: raw_products
      - name: raw_transactions
      - name: raw_product_views
      - name: raw_product_reviews
      - name: raw_member_interactions
